version: "3.9"
services:
  frontend:
    image: antonia123/aisafrontend:latest
    build: .    
    environment:
      - NODE_ENV=production
    container_name: aisa-app
    ports:
      - "8781:8781"  
    networks:
      - default
    depends_on:
      - backend 
    volumes:
      - /home/ubuntu/data:/app/data
      - /home/ubuntu/demodata:/app/demodata   

  backend: 
    image: antonia123/aisabackend:latest
    build: ./Backend
    container_name: aisa-data
    ports:
      - "8782:8782"
    networks:
      default: 
        ipv4_address: 172.16.238.10
    volumes:
      - /home/ubuntu/data:/R/data
      - /home/ubuntu/demodata:/R/demodata

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24
          gateway: 172.16.238.1