version: "3.9"
services:
  frontend:
    image: antonia123/aisafrontend:latest
    build: .    
    environment:
      - NODE_ENV=production
    container_name: aisa-app
    ports:
      - "8781:8781"  
    networks:
      - default
    #network_mode: "host"
    depends_on:
      - backend # wird erst gestartet, wenn auch backend erfolgreich gestartet werden könnte
    #links: 
    #  - backend

  backend: 
    image: antonia123/aisabackend:latest
    build: ./Backend
    container_name: aisa-data
    ports:
      - "8782:8782"
    networks:
      - default
    #network_mode: "host"
    volumes:
      - type: bind
        source: /home/ubuntu/AISA_GeosoftwareII/Backend
        target: /home/ubuntu/AISA_GeosoftwareII/Backend 

networks:
  default:
    driver: bridge
